version: '3.9'
services:

  db:
    image: postgres
    container_name: postgres-db-auction
    ports:
      - "5432:5432"
    env_file:
      - .env

  frontend:
      build: ./online_auction_frontend
      ports:
        - "3000:3000"
      depends_on:
        - python-backend
      volumes:
        - ./online_auction_frontend:/app 
      environment:
        - DISABLE_ESLINT_PLUGIN=true
        - CHOKIDAR_USEPOLLING=true

      
  java-backend:
    build: ./online_auction/java_backend
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    volumes:
      - ./online_auction/java-backend:/app


  python-backend:
    build: ./online_auction/python_backend
    ports:
      - "8000:8000"
    volumes:
      - ./online_auction/python_backend:/app
    depends_on:
      - db
    env_file:
      - .env